### ISSUE TITLE
git tags for versions 0.18.x and 0.19.x missing

### ISSUE THREAD

**Issue by jonas-schievink** [briansmith/webpki#101]
The [releases page](https://github.com/briansmith/webpki/releases) has not been updated since 0.17.0 has been released. Having git tags available that correspond exactly to a version on crates.io is very useful. Please consider publishing git tags for all releases ([`cargo-release`](https://github.com/sunng87/cargo-release) could also help automating this). Thanks!

**Comment by briansmith** [comment]
> Having git tags available that correspond exactly to a version on crates.io is very useful.

How are they useful? (Serious question, as I never used them myself, back when I was making them.)

**Comment by jonas-schievink** [comment]
I always like to make use of them when bisecting an issue or looking for bugs in dependencies. I know it's possible to download the source from crates.io directly, but that loses all connections with git.

For example, if something is working with 0.13.2 but not with 0.14.0, it's handy if there are git tags so I can easily see all commits between the versions. Ideally the tags would also have change logs attached so I don't even have to sieve through commits, but that takes a bit more effort to maintain.

Interestingly, I also can't recall ever making use of the git tags I create for my *own* projects. Apparently they're more useful to me when it's foreign code.

**Comment by briansmith** [comment]
Thanks for the suggestion. I think the only thing that really matters is whether the latest version works and whether the git master works. Until we get caught up with the backlog, I won't bother with the tagging. But, it will be something to do when we have more resources.
