### ISSUE TITLE
Uses alpha release of untrusted

### ISSUE THREAD

**Issue by est31** [briansmith/webpki#104]
Hi, it seems that the 0.20 release uses the release `0.7.0-alpha1` of untrusted. This seems like a bug to me.

**Comment by est31** [comment]
I've seen that since I've filed this, untrusted 7.0 was released and, ring 15.0 has been yanked from crates.io and master updated to use untrusted 7.0. Does this mean that I should wait with releasing an update of rcgen?

@briansmith what are your plans?

**Comment by briansmith** [comment]
Thanks for letting me know. This is fixed in 0.21.0.

**Comment by est31** [comment]
@briansmith thanks for the fixes!
