### ISSUE TITLE
Help with UnknownIssuer error

### ISSUE THREAD

**Issue by xmclark** [briansmith/webpki#108]
I'm attempting to use this crate indirectly through a new grpc crate (tonic). Tonic depends on rustls, rustls uses webpki. I would like to connect to my grpc server using TLS. I am *not* manually supplying the certificate. I am relying on Rustls and/or webpki (I think?) to fetch it for me.

When attempting to do grpc operations, I get an unhelpful error bubbled up through the error chain: `UnknownIssuer`. I was able to use my gdb debugger to inspect the problem. I narrowed it down to this section of `verify_cert.rs`: https://github.com/briansmith/webpki/blob/master/src/verify_cert.rs#L54-L56

By inspecting local variables, it appears that everything was working fine. Webpki was able to find the certificate and is comparing fields to the trust_anchor.  Webpki finally compares the cert issuer and the trust anchor subject, and decides they are not equivalent, and returns an `UnknownIssuer` error. 

I'm pretty uninformed about TLS and the specifications, so please forgive me! 🙏 . My questions:

Why does this comparison need to happen? 

Why could the cert I am using fail this assertion? 

I'm happy to attach the certificate if that would be useful. I'm also happy to open issues in another repo if this one is not appropriate. I'm also happy to hop on rust discord for offline conversation. Thanks!

**Comment by abelino** [comment]
I recently moved from `tls-native` to `rustls` and stated seeing this also. Here is an example where comparing the subject and issuer buffers fail. Data in hex:

```
31B30963554613255533115301363554A13C446967694365727420496E63311E301C6355431315446967694365727420476C6F62616C204341204732

31B30963554613255533115301363554A13C446967694365727420496E633119301763554B13107777772E64696769636572742E636F6D3120301E6355431317446967694365727420476C6F62616C20526F6F74204732
```

here are the two Input objects printed out
```
Input { value: Slice { bytes: [49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 21, 48, 19, 6, 3, 85, 4, 10, 19, 12, 68, 105, 103, 105, 67, 101, 114, 116, 32, 73, 110, 99, 49, 30, 48, 28, 6, 3, 85, 4, 3, 19, 21, 68, 105, 103, 105, 67, 101, 114, 116, 32, 71, 108, 111, 98, 97, 108, 32, 67, 65, 32, 71, 50] } }

Input { value: Slice { bytes: [49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 21, 48, 19, 6, 3, 85, 4, 10, 19, 12, 68, 105, 103, 105, 67, 101, 114, 116, 32, 73, 110, 99, 49, 25, 48, 23, 6, 3, 85, 4, 11, 19, 16, 119, 119, 119, 46, 100, 105, 103, 105, 99, 101, 114, 116, 46, 99, 111, 109, 49, 32, 48, 30, 6, 3, 85, 4, 3, 19, 23, 68, 105, 103, 105, 67, 101, 114, 116, 32, 71, 108, 111, 98, 97, 108, 32, 82, 111, 111, 116, 32, 71, 50] } }
```

**Comment by ctz** [comment]
These two are:

```
1 C=US, O=DigiCert Inc, CN=DigiCert Global CA G2
2 C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root G2
```

The first of these is an intermediate, the second is its issuing root cert. See the demo site for this CA: https://global-root-g2.chain-demos.digicert.com/

At a guess, your server is not providing a full certificate chain. If the server is on the internet, you can provide its URL to ssllabs.com and it will tell you if this is the case.

**Comment by abelino** [comment]
@ctz thanks for the nudge in the right direction. I've just started moving things to `rustls` and went back to the example client and noticed I didn't do one very important thing:

`tls.root_store.add_server_trust_anchors(&webpki_roots::TLS_SERVER_ROOTS);`

Sooo, error on my part. Once again thanks for the reply.

**Comment by xmclark** [comment]
`tls.root_store.add_server_trust_anchors(&webpki_roots::TLS_SERVER_ROOTS);` works for me! Thanks!

I think that solves my problem.
