### ISSUE TITLE
Unknown critical extensions are rejected too early

### ISSUE THREAD

**Issue by DemiMarie-parity** [briansmith/webpki#116]
If a certificate has an unknown critical extension, it is currently rejected at parse time.  That [breaks libp2p](/libp2p/specs/issues/241).

WebPKI obviously cannot verify that such a certificate is valid.  However, it should still be able to verify signatures made by the holder of such a certificate against the public key stored in the certificate.

**Comment by briansmith** [comment]
This happens when people try to use webpki for things it isn't intended to be used for. If you need to be able to extract the public key out of a certificate and use it, regardless of the certificate's validity according to Web PKI rules, then this crate isn't the one to use.
