### ISSUE TITLE
Does the intemediate certs is a must for CA chain verifications?

### ISSUE THREAD

**Issue by sammyne** [briansmith/webpki#126]
Hi, 

I'm playing with a scenario where there is a CA and server, without any intermediate ca between them, i.e. the server cert is signed directly by the root CA.

Due the limit enforced by this line https://github.com/briansmith/webpki/blob/master/src/verify_cert.rs#L80. It would report `UnknownIssuer` error~

Is there a standard saying that intermediate ca is a must?

If not, I think the loop in that line should be skipped in case of intermediate certs is empty.

Looking for your kind help~ 😄

**Comment by briansmith** [comment]
> Is there a standard saying that intermediate ca is a must?

Yes: https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.6.7.pdf

> 6.1.7. Key Usage Purposes
> Private Keys corresponding to Root Certificates MUST NOT be used to sign Certificates except in the following
cases:
> 1. Self-signed Certificates to represent the Root CA itself;
> 2. Certificates for Subordinate CAs and Cross Certificates;
> 3. Certificates for infrastructure purposes (administrative role certificates, internal CA operational > device
certificates); and
> 4. Certificates for OCSP Response verification

**Comment by sammyne** [comment]
I got you~ @briansmith 
Great thanks 😄
