### ISSUE TITLE
Allow using the end-entity public key for verifying signatures

### ISSUE THREAD

**Issue by briansmith** [briansmith/webpki#14]
Currently we don't provide access to the end-entity public key, so one cannot verify signatures (or do RSA decryption) using the public key. Thus, one can't implement TLS and other protocols on top of webpki.

Further, many IETF protocols and data formats use the common `SignedData` sub-structure for signed data. So, it would be useful to have access for `SignedData` and maybe `parse_signed_data` or some variant of it.

See @ctz's attempt at https://github.com/ctz/webpki/commit/7ac038109b98bd71e84abe2874f0b41ebe3d47bc

**Comment by briansmith** [comment]
Closed via https://github.com/briansmith/webpki/commit/83cec925886e4cae56c5d32e6335b7c96014a5a4.

This is pretty much the same as what @ctz did, but with additional documentation, and with the relevant API elements exposed directly from `webpki` instead of through `webpki::signed_data`.

Thanks @ctz for showing me how to do this!

**Comment by briansmith** [comment]
BTW, for TLS 1.2, it seems like we actually could use a lower-level API that takes a (`SignatureAlgorithm`, signed data, signature) triple instead of `SignedData`. In particular, `SignedData` assumes the signature algorithm is identified by an ASN.1 OID, but that isn't the case for TLS. So, we should probably add a better API.

**Comment by briansmith** [comment]
See https://briansmith.org/rustdoc/webpki/struct.EndEntityCert.html for the documentation of the new API. In particular, see https://briansmith.org/rustdoc/webpki/struct.EndEntityCert.html#method.verify_signature.

**Comment by ctz** [comment]
rustls is now using this new API. Thanks! :+1:

**Comment by briansmith** [comment]
Thanks! Looking at your code, I see that the documentation for `EndEntityCert::verify_signature` was wrong; I fixed it.

Thanks for reporting back.
