### ISSUE TITLE
Purposes for TrustAnchor instances

### ISSUE THREAD

**Issue by jsha** [briansmith/webpki#205]
Right now [TrustAnchor](https://docs.rs/webpki/0.21.4/webpki/struct.TrustAnchor.html) has the fields `subject`, `spki`, and `name_constraints`. Some trust stores have "trust bits" for various purposes (mainly TLS server vs email). I suspect it's implicit that `webpki` TrustAnchors are always considered to be trusted for authenticating TLS servers and TLS clients. Does it make sense to make that explicit in the documentation?

**Comment by briansmith** [comment]
When you pass the trust anchors into webpki, you have to wrap them either in `TLSServerTrustAnchors` or `TLSClientTrustAnchors`; i.e. this is explicit in the API already. I'm planning to refactor the API and when I do I intend to keep the distinction explicit in the types.
