### ISSUE TITLE
*BSD support

### ISSUE THREAD

**Issue by tymat** [briansmith/webpki#23]
Update dependency to ring 0.5.0 to add FreeBSD support:

https://github.com/briansmith/ring/issues/287

**Comment by briansmith** [comment]
Thanks. This will happen when *ring* 0.5 is published to crates.io, in 1-2 weeks.

**Comment by briansmith** [comment]
I published *ring* 0.5 and webpki 0.4, where webpki 0.4 depends on *ring* 0.5. Things should work on *BSD now. If not, let me know. Thanks!
