### ISSUE TITLE
Help debugging an UnknownIssuer error in PyOxidizer

### ISSUE THREAD

**Issue by rubendibattista** [briansmith/webpki#245]
Hello, sorry for the noob question. I'm trying to use the tool named [`pyOxidizer`][1] in a project within a corporate network with self-signed CA. The tool uses `reqwest` that uses `rusttls` that uses `webpki`. When downloading a package, I encounter the following problem: 

```
downloading https://github.com/indygreg/python-build-standalone/releases/download/20211017/cpython-3.9.7-x86_64-unknown-linux-gnu-pgo-20211017T1616.tar.zst
error[PYOXIDIZER_BUILD]: error sending request for url (https://github.com/indygreg/python-build-standalone/releases/download/20211017/cpython-3.9.7-x86_64-unknown-linux-gnu-pgo-20211017T1616.tar.zst): error trying to connect: invalid certificate: UnknownIssuer
```

For what I understand, the problem is probably coming from the certificate: 
`[snipped] for security`

`curl`-ing the package works as expected. 

any idea how I might fix this? Is this related to #241 ?

[1]: https://github.com/indygreg/PyOxidizer.git

**Comment by MattPColeman** [comment]
Did you resolve this in the end? I'm having an identical issue

**Comment by rdbisme** [comment]
Ehi @MattPColeman, at the end I gave up unfortunately. Anyway is someone is interested to work on this, I can provide the certificate. I think the problem here is some corner case on the self-signed certificate.
