### ISSUE TITLE
Add RSA-PSS support

### ISSUE THREAD

**Issue by briansmith** [briansmith/webpki#25]
Depends on, at least, https://github.com/briansmith/ring/pull/262.

The RSA-PSS tests imported from Chromium will need to be modified from expect-failure to expect-success.

One open question is whether to support SHA-1 as the MGF digest and/or whether to require the MGF digest algorithm to match the signature digest algorithm and/or whether to require the salt to be the length of the digest output. Certificates generated using Microsoft's tools only use SHA-1 with 20-byte salts.

**Comment by briansmith** [comment]
This is necessary for full TLS 1.3 support in theory because:

1. The server will use RSA-PSS instead of RSA-PKCS#1 for its signature in the TLS handshake in TLS 1.3.
2. A TLS 1.3 implementation will advertise support for RSA-PSS and this might induce the server to send a PSS-signed certificate instead of a certificate with some other supported signature algorithm.

/ cc @ctz.

**Comment by ctz** [comment]
I've had a go at doing this, but I can't find any tests that have saltLen == hLen and a supported hash function :(

**Comment by briansmith** [comment]
> I've had a go at doing this, but I can't find any tests that have saltLen == hLen and a supported hash function :(
> 
> (edit: that is, for actual certificates. I'd be perfectly happy if all PSS-using certificates were safely rejected as long as verify_signature works with PSS.)

That's expected. Right now, almost all PSS certificates are generated by Windows's certificate stuff, which only supports MGF1 using SHA-1 with a 20-byte salt. However, it shouldn't be too difficult to modify one of the currently-disabled PSS tests to add support for the supported parameters.

**Comment by ctz** [comment]
Not ready for a PR yet, but this is the current state of things:

https://github.com/ctz/webpki/commit/814d5d6dfa375c305297a4ebba9cc1be021abf25

**Comment by briansmith** [comment]
> ctz@814d5d6

Despite RFC 4055 saying "Implementations that perform signature validation MUST recognize both a present trailerField field with value 1 and an absent trailerField field," I suggest you drop the support for the explicit trailer field unless you know it is necessary to interop with some implementation. (If so, please include some comments to that effect.), because:
* The spec says "Implementations that perform signature generation MUST omit the trailerField field, indicating that the default trailer field value was used" and I'd like to start out trying to enforce that.
* The ASN.1 says that 1 is the default value and in DER it isn't allowed to encode the default value explicitly.
* I am hoping at some point we'll be able to get rid of the "optional NULL" support for PKCS#1 1.5 signatures so that every algorithm will have exactly one possible encoding in every context.

It looks like RFC 4055 wants us to be more flexible in matching salt lengths but I think we're going to try to avoid doing that too, at least until it is shown to be problematic. Being able to do bytewise comparison of the algorithm parameters—and eventually the entire algorithm identifier—is a significant simplification of the code.

**Comment by briansmith** [comment]
FWIW, I also added this as an issue for Mozilla's CA policy: https://github.com/mozilla/pkipolicy/issues/37 (also https://github.com/mozilla/pkipolicy/issues/38).

**Comment by briansmith** [comment]
This was done in #32 by @ctz. Thanks again!
