### ISSUE TITLE
Err(UnknownIssuer) occurred when verifying certificate chain

### ISSUE THREAD

**Issue by YT-SUN97** [briansmith/webpki#262]
Hi, I am a beginner and quite confused about this. I tried to verify a cert chain (2 certs, root ca cert signed end-entity cert). 
First, I cloned the repo, added my test case, and used the `cargo test,` The result was passed (ok).
After that, I tried to call API(I wrote the same code, referred to [this](https://github.com/briansmith/webpki/blob/b481381e914de604df30b1be2fe72d938a5c0e57/tests/integration.rs#L57) fn in this repo). But it failed with `Err(UnknownIssuer).`
Can someone give me some advice? I really appreciate any help you can provide.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/33065600/174139222-47a804ee-6a98-42ad-b72d-7b79c2fc7755.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/33065600/174139319-e12dc537-f758-471b-b270-3b0b1df13098.png">

**Comment by YT-SUN97** [comment]
Finally, I solved it.
Let's close the issue.

**Comment by bojankaios** [comment]
How to solve it? Thanks
