### ISSUE TITLE
[Question] How does webpki decide if a common name is a DirectoryName instead of DNSName?

### ISSUE THREAD

**Issue by tjamaan** [briansmith/webpki#42]
I have the common name `my_controller_1.server` which is failing cert validation because `webpki` thinks it's a `name::GeneralName::DirectoryName` instead of a `name::GeneralName::DNSName` when it's doing verification in `name::verify_cert_dns_name`.

How does `webpki` decide if a name like `my_controller_1.server` is a DirectoryName or a DNSName? As far as I can tell that could be a legitimate DNS name (I don't think it violates RFC6125).

**Comment by briansmith** [comment]
webpki ignores the Common Name field of the Subject of the certificate. Instead it looks at dNSName entries in the subjectAltNames extension. You need to add the subjectAltNames extension to your certificates, with a dNSName entry.
