### ISSUE TITLE
Source of BadDER

### ISSUE THREAD

**Issue by KenMacD** [briansmith/webpki#47]
Hello,

In some test code I'm using locally generated certificates. When I try to connect to a service using one of these certificates I'm getting the error `BadDER`. Unfortunately that's all I can seem to get, and when looking at the code it seems these could be generated in one of many places.

Is there any way to narrow down exactly what went wrong?

**Comment by briansmith** [comment]
You can use https://github.com/awslabs/certlint on the certificate to find out what's wrong with it.

**Comment by KenMacD** [comment]
That showed that the certificate is `v1`, which I had also found independently. The problem is that there's a ton of places in the code that could return this error, making it very hard to figure out what went wrong.

**Comment by briansmith** [comment]
> That showed that the certificate is v1, which I had also found independently. The problem is that there's a ton of places in the code that could return this error, making it very hard to figure out what went wrong.

I agree. The original (current) design philosophy of the webpki crate is that it should do the minimum amount of work to tell you that the certificate is good or bad. It's not intended to be an investigative tool for finding out why a certificate is bad. Some library try to do both, but IMO the applications that use them are worse off for that. I hope at some point some to write documentation about this.

RE: v1 certificates, again they are rejected intentionally to follow the design philosophy, which is to enforce good practices. v1 certificates simply can't follow best practices. In particular, if you were to replace that v1 certificate with a v3 certificate with no other changes, then you'd run into other places where that certificate is doing the wrong thing, namely that it doesn't have a subjectAltName extension.

Unfortunately, the defaults for OpenSSL's (and many other librarys') certificate generation is to make, basically, the worst possible certificates one can make. People are working on better alternatives.

**Comment by steffengy** [comment]
I'm getting the same error for a default (microsoft sql server on windows) self-generated v3-certificate 
where certlint returns:
```
Unicode commonName is using deprecated BMPString
```

Certificate Data as extracted from the TLS-handshake (don't mind the txt extension):
 [cert_without_len.txt](https://github.com/briansmith/webpki/files/1016099/cert_without_len.txt)

Is returning `WebPKIError(BadDER)` for that certificate the intended behavior?
