### ISSUE TITLE
Comment in verify_cert.rs points at non-existant function

### ISSUE THREAD

**Issue by alex** [briansmith/webpki#55]
https://github.com/briansmith/webpki/blob/master/src/verify_cert.rs#L150-L151

I can't seem to actually find a `remember_extensions` function

**Comment by briansmith** [comment]
Thanks. It's `remember_extension`: https://github.com/briansmith/webpki/blob/8d3309988dc37605708768af60760443c1c2e14d/src/cert.rs#L171-L175

**Comment by briansmith** [comment]
This was fixed by @alex's commit in 748c8e24b3e9f5f4e3efd7fbb793586be5cb4c1a. Thanks!
