### ISSUE TITLE
Build Rust documentation with every push to the default branch

### ISSUE THREAD

**Issue by frewsxcv** [briansmith/webpki#7]
Now that https://github.com/huonw/travis-cargo/pull/17 has merged, travis-cargo should work with this project. Prior to that PR, it only supported building docs on branches named master.

**Comment by briansmith** [comment]
Hi, I decided not to use travis-cargo for this, for a variety of reasons. Instead, I'm going to manage the publication of the documentation for libwebpki the same way I manage it for [*ring*](https://github.com/briansmith/ring). Thanks for the suggestion, though!

**Comment by frewsxcv** [comment]
Sounds good
