### ISSUE TITLE
Bump untrusted version for security

### ISSUE THREAD

**Issue by tirkarthi** [briansmith/webpki#74]
Hi,

This project seems to use `untrusted = 0.6.1` as I can see from the cargo.toml file on master branch. Recently a security issue was fixed as part of 0.6.2 release. Please refer to https://github.com/RustSec/advisory-db/commit/3c0458d26bd19e30dc19ae5ca9a4540cc9c0394b . 

Kindly ignore if this is irrelevant or fixed on another branch.

Thanks.

Edit : Just noticed that you are the author of the untrusted library.

**Comment by briansmith** [comment]
Thanks! I did this in the latest release.
