### ISSUE TITLE
`EndEntityCert` should expose all certificate fields or inner data

### ISSUE THREAD

**Issue by akuanti** [briansmith/webpki#77]
Currently, `webpki` only parses certificates enough to verify them, and does not make the parsed data available to users. This means that, for example, there is no clear way to get certificate information such as the subject (common name, organization name, etc) from the certificate, which applications might need.

I *would* parse it directly from `Cert::subject`, etc., using `ring`, but the inner `Cert` is private in `EndEntityCert`, so I don't have access to it. I could also parse the entire certificate again from scratch, but it seems unnecessary to parse it again if `webpki` is already at least partially parsing it once. I would rather continue parsing from where `webpki` left off. `EndEntityCert` also does not have functions to access the fields of the certificate.

It would be really nice if there was a simple public function to parse `untrusted::Input` into a `Cert`, or if the inner `Cert` was public, or if `EndEntityCert` exposed the fields of the certificate as typed data that I could use directly.

**Comment by briansmith** [comment]
Thanks for the request. If we need specific items from the certificate (e.g. the subject), let's file individual issues for those specific items. That way we can design the API carefully for each one and write tests, etc.

**Comment by akuanti** [comment]
Can you provide clarification on what sorts of changes you would be okay with? Would these be exposed as methods on `EndEntityCert` or elsewhere? I am also curious about what sorts of concerns you are taking into account in thinking about what to expose and how to expose it.
