### ISSUE TITLE
X.509 ceritificate builder?

### ISSUE THREAD

**Issue by seamlik** [briansmith/webpki#93]
Any plan to support constructing an X.509 certificate?

Right now a project of mine designs a embeded P2P client that issues and verifies certificates, and had to depend on 2 TLS libraries (OpenSSL for issuance and `quinn` + Rustls for verification). Would be great to get rid of one of them.

**Comment by djc** [comment]
Have a look at https://github.com/est31/rcgen.

**Comment by seamlik** [comment]
Just realized that you @djc contributed the feature to that crate. Thank you very much!
